### ISSUE TITLE
PhantomJS with Mocha is not executing unit test on custom or hosted agents

### ISSUE THREAD

**Issue by SebastianSchuetze** [pnp/sp-dev-build-extensions#34]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@baywet 

## Expected or Desired Behavior

The unit tests with  mocha are succeeding and a unit test result file is generated in the build pipeline (yaml or json based, does not matter)

## Observed Behavior

When using a private agent or the hosted VS 2017 is used that PhantomJS server is unrespinsive when it is running. So no unit test can run. It gets cancelled after 60 second:

![image](https://user-images.githubusercontent.com/7256168/52882298-81c3dc00-3167-11e9-8328-29275add33bb.png)

See here for the problem:
https://github.com/karma-runner/karma-phantomjs-launcher/issues/112

The solution was to add a build variable as the following 
PHANTOMJS_BIN = C:\NPM\Modules\PhantomJS.cmd

But that does not seem to work anymore, but was before. My first guess is, that it has to do with VS installed on the agent? Because it seems to work for the hosted agent without VS.

## Steps to Reproduce

1. Setup Pipeline (yaml or JSON)
2. use a private agent with VS 2017, nodejs, npm, newest PS version installed
    a. alternatively use the hosted VS 2017 agent
3. run the build 
4. see the warning for step "gulp test", but the build succeeds without outputting the unit test results

**Comment by baywet** [comment]
thanks for reporting that Sébastian!
Do you know for how long the problem has been around?
Are you having the same problem using the ubuntu agent?

**Comment by SebastianSchuetze** [comment]
I actually don't know. But my guess is, that it doesn't work since at least 2-3 month. Or in other words: I am not sure if it ever worked since this pipeline exists, unfortunately.

I haven't tried it on an ubuntu agent. But let me check now.

**Comment by SebastianSchuetze** [comment]
I just tried it. It does not work:

![image](https://user-images.githubusercontent.com/7256168/53162959-6294d680-35cd-11e9-8e82-352e739d5930.png)

**Comment by baywet** [comment]
could you provide a sample of a project/unit test that fails?

**Comment by SebastianSchuetze** [comment]
> could you provide a sample of a project/unit test that fails?

Not entirely sure what you mean, but I used the exact sample without any changes from this repository and the unchanged build pipeline. I think the problem lies more with the agent itself. 

So which agent pools work:
- Hosted

Agents that do not work:

- Hosted VS 2017
- Hosted Ubuntu 1604
- my private one hosted in a VM in Azure with my custom installation

not tested:
- Hosted Windows Container based Agent
- Hosted Mac Agent

**Comment by baywet** [comment]
Sorry for the delay in the reply.
I ran a couple of tests on net new projects, old projects I've been using for demonstrations, professional existing projects, on different tenants and different pools.
So far I haven't been able to reproduce the issue.
The only different I can think of right now would be that all my Azure DevOps tenants are located in North America, but I'm not sure that'd make a big difference.
Can you think about anything else that might explain the difference in behavior between my tenants and your tenant?
Can you run phantomjs tests outside of SharePoint Framework projects?
![image](https://user-images.githubusercontent.com/7905502/53385571-d8da6580-394c-11e9-87de-aefd121cd89b.png)

**Comment by SebastianSchuetze** [comment]
closing this as I am not working with SP Framework anymore
